### ISSUE TITLE
Configurable tombstone function name

### ISSUE THREAD

**Issue by scheb** [scheb/tombstone#5]
# Idea

Currently the tombstone function name is hardcoded to `tombstone` (a function within the global scope). Make that function configurable and allow having multiple tombstone functions. Multiple tombstone functions would provide more flexibility, e.g.

- You don't want a function in the global scope, but use something namespaced instead
- Have a function that always logs invocations vs. have a function that randomly logs (sampling)
- Use different tombstones for different purposes

**If this idea would be useful to you, give it a +1**

# Todo

- [x] Add function name to Tombstone class
- [x] Log tombstone function name
- [x] Add analyzer config option for tombstone functions names, pass these to the extractor
- [x] Add analyzer config option to use tombstone function name for matching tombstones (or not, to treat all tombstone functions as if they're all the same function)

**Comment by scheb** [comment]
Feature released with v1.3.0.
